MA-7879 replace index() with strchr() to pass build on 64bit platform
Index() is removed in 64bit binary, replacing an index() call with
the equivalent strchr() to solve the build issue.

Background information about this issue as below:

Meet below build error when do 64bit build on imx8dv.Root cause is index()
function is removed from 64-bit binary, below commit in android bionic.git
include some detail information, as this commit said we can replace an index()
call with the equivalent strchr() as they are the same functionality.

external/linux-test/test/mmdc/mmdc.c:251:3: error: implicit declaration
of function 'index' [-Werror=implicit-function-declaration]

commit 891dedb935b50f1abb39eedfe33049a1e49283cb
Author: David 'Digit' Turner <digit@google.com>
Date:   Fri Jun 13 12:28:11 2014 +0200

    libc: Fix 'index' symbol export.

    The C library didn't export the 'index' symbol, but its C++ name-mangling
    instead, which broke the ABI and prevented some applications from loading
    properly.

    The main reason was that the implementation under bionic/index.cpp relied
    on the declaration to specify that the function has C linkage.

    However, the declaration for index() was removed from both <string.h>
    and <strings.h> in a recent patch, which made the compiler think it was
    ok to compile the function with C++ linkage instead!

    This patch does the following:

    - Move index() definition to bionic/ndk_cruft.cpp and ensure it uses
      C linkage.

      Note that this removes index() from the 64-bit library entirely, this
      is intentional and will break source compatibility. Simply replacing
      an index() call with the equivalent strchr() should be enough to fix
      this in third-party code.

    - Remove bionic/index.cpp from the tree and build files.

    - Remove x86 assembly implementation from arch-x86/ to avoid conflict
      with the one in ndk_cruft.cpp

    BUG=15606653

    Change-Id: I816b589f69c8f8a6511f6be6195d20cf1c4e8123

Signed-off-by: Richard Liu <xuegang.liu@nxp.com>